# Generated by Django 4.2.5 on 2023-11-17 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0022_alter_extendeddata_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='respuesta_seguridad',
        ),
    ]
