# Generated by Django 4.2.5 on 2023-11-17 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0023_remove_profile_respuesta_seguridad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extendeddata',
            name='respuesta_seguridad',
        ),
        migrations.AddField(
            model_name='profile',
            name='pregunta_seguridad',
            field=models.CharField(choices=[('1', '¿Cuál es el nombre de tu primera mascota?'), ('2', '¿Cuál es tu ciudad de nacimiento?'), ('3', '¿Cuál es tu libro favorito?')], default='', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='respuesta_seguridad',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extendeddata',
            name='user',
            field=models.OneToOneField(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='extendeddata',
            name='user_type',
            field=models.CharField(choices=[('A', 'Artista'), ('S', 'Sponsor')], default='', max_length=1),
        ),
    ]
