# Generated by Django 4.2.5 on 2023-11-17 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0024_remove_extendeddata_respuesta_seguridad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeddata',
            name='user_type',
            field=models.CharField(choices=[('A', 'Artista'), ('S', 'Sponsor')], default='', max_length=1, null=True),
        ),
    ]
