# Generated by Django 4.2.5 on 2023-11-18 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0025_alter_extendeddata_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeddata',
            name='user_type',
            field=models.CharField(choices=[('A', 'Artista'), ('S', 'Sponsor')], max_length=1, null=True, verbose_name='tipo de usuario'),
        ),
    ]
