# Generated by Django 4.2.4 on 2023-11-19 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0026_alter_extendeddata_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeddata',
            name='pregunta_seguridad',
            field=models.CharField(choices=[('1', '¿Cuál es el nombre de tu primera mascota?'), ('2', '¿Cuál es tu ciudad de nacimiento?'), ('3', '¿Cuál es tu libro favorito?')], default='', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='extendeddata',
            name='respuesta_seguridad',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
